### ISSUE TITLE
If/else

### ISSUE THREAD

**Issue by jackfearing** [BIOSTALL/ACF-Link-Picker-Field#15]
Is there a reason why if/else statements don't work with the plugin? The reason I ask is because I need to wrap the link around another ACF field in some case and in other instances if the link is not present, don't wrap the link around the field.
![screen shot 2015-10-13 at 4 52 00 pm](https://cloud.githubusercontent.com/assets/6834687/10471450/c26cf1f2-71ca-11e5-837a-e539c6cb8d0d.png)

**Comment by JanKopietzGit** [comment]
Hi there. I solved this issue by checking if a url is set in the link field like this:

`if(get_sub_field('link_field')['url']) { 
     echo 'Link is set';
} else { 
     echo 'Link is not set';
}`

Greetings
