### ISSUE TITLE
ACF5 / Editing Link

### ISSUE THREAD

**Issue by gamma-dj** [BIOSTALL/ACF-Link-Picker-Field#7]
On ACF5, within a repeater field, when clicking "edit" on an existing link brings up the Link dialog without the current value - just as though we're adding a link for the first ever time.

I've only tested within a repeater so far

**Comment by khromov** [comment]
@gamma-dj There's no code for picking up old values, so that doesn't work at all right now. Looking into that though as I need it as well. :)
